# Generated by Django 3.2 on 2022-02-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0002_auto_20220208_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('time', models.TimeField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('booking_status', models.IntegerField(choices=[(0, 'Booked'), (1, 'Availble')], default=1)),
                ('tables', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='bookingsys.table')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 1}, related_name='booking_table_slot', to='bookingsys.BookingSlot'),
        ),
    ]
