# Generated by Django 3.2 on 2022-02-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0004_rename_tables_bookingslot_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='table',
            new_name='tables',
        ),
    ]
