# Generated by Django 3.2 on 2022-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0007_bookingslot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
