# Generated by Django 3.2 on 2022-02-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0009_rename_tables_bookingslot_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TSlot',
            new_name='TimeSlot',
        ),
    ]
