# Generated by Django 3.2 on 2022-02-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0010_rename_tslot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='timeSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingslot', to='bookingsys.timeslot'),
        ),
    ]
