# Generated by Django 3.2 on 2022-02-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0011_alter_bookingslot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ManyToManyField(blank=True, limit_choices_to={'booking_status': 1, 'status': 1}, related_name='booking_table_slot', to='bookingsys.BookingSlot'),
        ),
    ]
