# Generated by Django 3.2 on 2022-02-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0012_alter_booking_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingslot',
            old_name='timeSlot',
            new_name='time_slot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booked'), (1, 'Cancelled'), (2, 'Redeemed')], default=0),
        ),
    ]
