# Generated by Django 3.2 on 2022-02-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0013_auto_20220208_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_of_booking']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_on',
            new_name='date_of_booking',
        ),
    ]
