# Generated by Django 3.2 on 2022-02-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0014_auto_20220208_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='time_slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'closed': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingslot', to='bookingsys.timeslot'),
        ),
    ]
