# Generated by Django 3.2 on 2022-02-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0016_auto_20220209_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
