# Generated by Django 3.2 on 2022-02-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0018_alter_booking_number_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='closed',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booked'), (1, 'Cancelled'), (2, 'Attended')], default=0),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='time_slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingslot', to='bookingsys.timeslot'),
        ),
    ]
