# Generated by Django 3.2 on 2022-02-10 16:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0020_auto_20220210_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_capacity',
            field=models.IntegerField(default=builtins.id),
        ),
    ]
