# Generated by Django 3.2 on 2022-02-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0022_alter_table_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='time_slot',
            field=models.ForeignKey(default='', limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='bookingslot', to='bookingsys.timeslot'),
        ),
    ]
