# Generated by Django 3.2 on 2022-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0023_alter_bookingslot_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ManyToManyField(default='', limit_choices_to={'booking_status': 1, 'status': 1}, related_name='booking_table_slot', to='bookingsys.BookingSlot'),
        ),
    ]
