# Generated by Django 3.2 on 2022-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0024_alter_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
