# Generated by Django 3.2 on 2022-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0025_alter_booking_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='guest@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='first name', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='last name', max_length=20),
        ),
    ]
