# Generated by Django 3.2 on 2022-02-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0027_rename_guest_booking_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_of_booking',
            new_name='date_created',
        ),
    ]
