# Generated by Django 3.2 on 2022-02-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0028_auto_20220211_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('table', 'date', 'time_slot')},
        ),
    ]
