# Generated by Django 3.2 on 2022-02-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0030_auto_20220211_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
