# Generated by Django 3.2 on 2022-07-10 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0032_remove_booking_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ManyToManyField(default='', limit_choices_to={'booking_status': 1, 'date__range': (datetime.date(2022, 7, 10), datetime.date(2022, 8, 9)), 'status': 1}, related_name='booking_table_slot', to='bookingsys.BookingSlot'),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Table Deleted'), related_name='timeslot', to='bookingsys.table'),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='time_slot',
            field=models.ForeignKey(default='', limit_choices_to={'status': 1}, on_delete=models.SET('TimeSlot Deleted'), related_name='bookingslot', to='bookingsys.timeslot'),
        ),
    ]
