# Generated by Django 3.2 on 2022-07-17 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsys', '0036_alter_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ManyToManyField(default='', limit_choices_to={'booking_status': 1, 'date__range': (datetime.date(2022, 7, 17), datetime.date(2022, 8, 16)), 'status': 1}, related_name='booking_table_slot', to='bookingsys.BookingSlot'),
        ),
    ]
