# Generated by Django 3.2 on 2022-07-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
